### ISSUE TITLE
rdf:listの要素を取得するためのクエリについて質問

### ISSUE THREAD

**Issue by s246wv** [LinkedOpenData/QAaboutLODC#7]
[ナレッジグラフ推論チャレンジ](https://github.com/KnowledgeGraphJapan/KGRC-RDF/tree/kgrc4si)のRDFデータから`:Object`のバウンディングボックスを取得しようとしていますが，クエリの書き方についてご指導いただけると幸いです．
[こちらのサイト](http://www.snee.com/bobdc.blog/2014/04/rdf-lists-and-sparql.html)を参考に次の2パターンでクエリを記載し実行しました．
パターン1
```SPARQL
prefix ex: <http://example.org/virtualhome2kg/instance/> 
prefix x3do: <https://www.web3d.org/specifications/X3dOntology4.0#> 
select distinct * where { 
	?state vh2kg:bbox ?shape;
        vh2kg:isStateOf ?object.
    ?shape x3do:bboxCenter ?bboxCenter;
           x3do:bboxSize ?bboxSize;
           a x3do:Shape.
    ?bboxCenter rdf:rest*/rdf:first ?BCXYZ.
    ?bboxSize rdf:rest*/rdf:first ?BSXYZ.
    filter(?shape = ex:shape_state0_character1_admire_paintings_scene1)
}
```
パターン2
```SPARQL
prefix ex: <http://example.org/virtualhome2kg/instance/> 
prefix x3do: <https://www.web3d.org/specifications/X3dOntology4.0#> 
select distinct * where { 
	?state vh2kg:bbox ?shape;
        vh2kg:isStateOf ?object.
    ?shape x3do:bboxCenter ?bboxCenter;
           x3do:bboxSize ?bboxSize;
           a x3do:Shape.
    ?bboxCenter rdf:first ?BCX.
    ?bboxCenter rdf:rest/rdf:first ?BCY.
    ?bboxCenter rdf:rest/rdf:rest/rdf:first ?BCZ.
    ?bboxSize rdf:first ?BSX.
    ?bboxSize rdf:rest/rdf:first ?BSY.
    ?bboxSize rdf:rest/rdf:rest/rdf:first ?BSZ.
    filter(?shape = ex:shape_state0_character1_admire_paintings_scene1)
}
```

パターン1では，リストの全要素を取得可能ですが，得られた値がリストのインデックスの何番目かがわかりません．
パターン2では，リストの2番目の要素（バウンディングボックスのY座標に相当すると思われるもの）が正しく取得できません．
結果の一部を下記に示します．
<html>
<body>

-- |state | shape | object | bboxCenter | bboxSize | BCX | BCY | BCZ | BSX | BSY | BSZ
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | ex:state0_character1_admire_paintings_scene1 | ex:shape_state0_character1_admire_paintings_scene1 | ex:character1_scene1 | _:node7563 | _:node7566 | "4.878775e+00"^^xsd:double | time:TemporalDuration | "-6.775291e+00"^^xsd:double | "6.934643e-01"^^xsd:double | time:TemporalDuration | "1.869719e+00"^^xsd:double
2 | ex:state0_character1_admire_paintings_scene1 | ex:shape_state0_character1_admire_paintings_scene1 | ex:character1_scene1 | _:node7563 | _:node7566 | "4.878775e+00"^^xsd:double | time:TemporalDuration | "-6.775291e+00"^^xsd:double | "6.934643e-01"^^xsd:double | time:TemporalEntity | "1.869719e+00"^^xsd:double
3 | ex:state0_character1_admire_paintings_scene1 | ex:shape_state0_character1_admire_paintings_scene1 | ex:character1_scene1 | _:node7563 | _:node7566 | "4.878775e+00"^^xsd:double | time:TemporalDuration | "-6.775291e+00"^^xsd:double | "6.934643e-01"^^xsd:double | _:node6 | "1.869719e+00"^^xsd:double
4 | ex:state0_character1_admire_paintings_scene1 | ex:shape_state0_character1_admire_paintings_scene1 | ex:character1_scene1 | _:node7563 | _:node7566 | "4.878775e+00"^^xsd:double | time:TemporalDuration | "-6.775291e+00"^^xsd:double | "6.934643e-01"^^xsd:double | _:node9 | "1.869719e+00"^^xsd:double

</body>
</html>

トリプルストアはGraphDBを使いました．

SPARQL クエリに見識の深い方々のご教授を頂ければ幸いに思います．

**Comment by Ease112** [comment]
@s246wv さん
ナレッジグラフ推論チャレンジ【実社会版】に興味を持ってくださりありがとうございます。
ご質問の件について、ご不便おかけしており申し訳ございません。
こちらでも同じデータ、トリプルストア、クエリを使用して現象を確認しました。
Y座標の値が取れない件について、奇妙な結果となっている根拠をうまく説明することができず恐縮ですが、プロパティパスを使用時にリスト要素に与えられるブランクノードを正しく特定できていないように推察します。（どなたか詳しい方補足頂けましたら幸いです）
少しクエリが長くなってしまいますが、下記のようにプロパティパスを使わないクエリですと、正しい結果を取得することができます。
```SPARQL
prefix ex: <http://example.org/virtualhome2kg/instance/> 
prefix x3do: <https://www.web3d.org/specifications/X3dOntology4.0#> 
PREFIX vh2kg: <http://example.org/virtualhome2kg/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
select distinct ?state ?shape ?object ?BCX ?BCY ?BCZ ?BSX ?BSY ?BSZ where { 
	?state vh2kg:bbox ?shape;
        vh2kg:isStateOf ?object.
    ?shape x3do:bboxCenter ?bboxCenter;
           x3do:bboxSize ?bboxSize;
           a x3do:Shape.
    ?bboxCenter rdf:first ?BCX.
    ?bboxCenter rdf:rest ?BCYb .
    ?BCYb rdf:first ?BCY ;
          rdf:rest ?BCZb .
    ?BCZb rdf:first ?BCZ .
    ?bboxSize rdf:first ?BSX.
    ?bboxSize rdf:rest ?BSYb .
    ?BSYb rdf:first ?BSY  ;
          rdf:rest ?BSZb .
    ?BSZb rdf:first ?BSZ .
    filter(?shape = ex:shape_state0_character1_admire_paintings_scene1)
}
```
|   |                     state                    |                        shape                       |        object        |             BCX            |             BCY            |             BCZ             |             BSX            |             BSY            |            BSZ            |
|:-:|:--------------------------------------------:|:--------------------------------------------------:|:--------------------:|:--------------------------:|:--------------------------:|:---------------------------:|:--------------------------:|:--------------------------:|:-------------------------:|
| 1 | ex:state0_character1_admire_paintings_scene1 | ex:shape_state0_character1_admire_paintings_scene1 | ex:character1_scene1 | "4.878775e+00"^^xsd:double | "2.121052e+00"^^xsd:double | "-6.775291e+00"^^xsd:double | "6.934643e-01"^^xsd:double | "1.869719e+00"^^xsd:double | "1.40602e+00"^^xsd:double |

ご参考になりましたら幸いです。
よろしくお願いいたします。

**Comment by s246wv** [comment]
お忙しい中早速のお返事を頂きありがとうございます．
> 少しクエリが長くなってしまいますが、下記のようにプロパティパスを使わないクエリですと、正しい結果を取得することができます。

`rdf:rest`と`rdf:first`をバラバラにすればよかったのですね．ありがとうございます😊
